import { type ReactNode, useEffect } from "react";
import { usePipelineContext } from "../pipeline/PipelineContext";
import type { ClipLabItemRef, Project } from "../types";
import WorkspaceStatePanel from "../workspace/WorkspaceStatePanel";

type LabPageProps = {
  activeProject: Project | null;
  activeClipItem: ClipLabItemRef | null;
  projectLoadStatus: "loading" | "ready" | "error";
  projectLoadError: string | null;
  onActiveClipItemChange: (clipItem: ClipLabItemRef | null) => void;
  onRetryProjects: () => void;
  onHeaderActionsChange: (actions: ReactNode) => void;
};

export default function LabPage({
  activeProject,
  projectLoadStatus,
  projectLoadError,
  onActiveClipItemChange,
  onRetryProjects,
  onHeaderActionsChange,
}: LabPageProps) {
  const { selectedLabDatasetRunId } = usePipelineContext();

  useEffect(() => {
    onActiveClipItemChange(null);
    onHeaderActionsChange(null);
  }, [onActiveClipItemChange, onHeaderActionsChange]);

  if (projectLoadStatus === "error") {
    return (
      <WorkspaceStatePanel
        title="Projects unavailable"
        message={projectLoadError ?? "Project load failed."}
        actionLabel="Retry"
        onAction={onRetryProjects}
      />
    );
  }
  if (projectLoadStatus === "loading") {
    return <WorkspaceStatePanel title="Loading projects" message="Fetching project context." />;
  }
  if (!activeProject) {
    return <WorkspaceStatePanel title="No project selected" message="Select a project before opening candidate review." />;
  }

  return (
    <section className="step-page pipeline-page lab-page-shell">
      <div className="panel pipeline-hero">
        <p className="eyebrow">Candidate Lab</p>
        <h2>Dataset candidate review is the next build target</h2>
        <p>
          The old Clip Lab depended on Slice, AudioVariant, Transcript, EditCommit, and QCRun rows generated by the
          legacy source-level slicer. That path is no longer authoritative and is intentionally not mounted here.
        </p>
        <p>
          The replacement should consume `candidate_review_manifest.json`, native export clips, and
          `candidate_review_decisions.json` for accepted/rejected/needs-edit decisions.
        </p>
        <div className="button-row">
          <span className="status-pill">Selected dataset run: {selectedLabDatasetRunId ?? "none"}</span>
        </div>
      </div>
    </section>
  );
}
